export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const LOGOUT = "LOGOUT";
export const FETCH_EMPLOYEES = "FETCH_EMPLOYEES";
export const MODIFY_EMPLOYEES = "MODIFY_EMPLOYEES";
export const CREATE_EMPLOYEE = "CREATE_EMPLOYEE";
